import Head from "next/head";
import { ReactNode } from "react";
import styles from "./AuthLayout.module.css";
import {Menu} from "@/components/auth/navbar/Menu";
import { TokenContextProvider } from "@/context";

interface authLayoutProps {
    children: ReactNode,
    title: string
}

export function AuthLayout ({children, title}: authLayoutProps):JSX.Element {

    return(
        <div className={styles.wrapper}>
            <TokenContextProvider>
                <Head>
                    <title>{title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                
                <Menu/>
                {children}
            </TokenContextProvider>
        </div>
    )
}