import { Footer, Header} from "@/modules";
import {DetailedHTMLProps, HTMLAttributes, ReactNode } from "react";
import Head from 'next/head';
import { TokenContextProvider } from "@/context";

interface layoutProps extends DetailedHTMLProps<HTMLAttributes<HTMLDivElement>,HTMLDivElement>{
    children: ReactNode,
}

export const Layout = ({children}:layoutProps):JSX.Element=>{

    return(
        <>
            <Head>
                <title> Nomads Treval </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <main>
                {children}
            </main>
            <Footer/>
        </>
    )
}