import { Footer, Header} from "@/modules";
import styles from "./Layout.module.css";
import {DetailedHTMLProps, HTMLAttributes, ReactNode } from "react";
import Head from 'next/head';
import { TokenContextProvider } from "@/context";

interface layoutProps extends DetailedHTMLProps<HTMLAttributes<HTMLDivElement>,HTMLDivElement>{
    children: ReactNode,
}

export const Layout = ({children}:layoutProps):JSX.Element=>{

    return(
        <main className={styles.wrapper}>
            <TokenContextProvider>
                <Head>
                    <title>Nomads Treval</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header/>
                {children}
                <Footer/>
            </TokenContextProvider>
        </main>
    )
}